var template = {
	edit:{
		title:'服务表',
		width:650,
		height:480,
		sqlKey:'serviceInfo.DB',
		id:'serviceId',
		cascade:true,
		items:[
			{
				xtype:'hidden',
				name:'serviceId',
				value:'NULL'
			},
			{
				xtype:'clearTextField',
				fieldLabel:'类别id',
				name:'serviceCategoryId',
				value:''
			},
			{
				xtype:'clearTextField',
				fieldLabel:'类别名称',
				name:'serviceCategoryName',
				value:''
			},
			{
				xtype:'clearTextField',
				fieldLabel:'名称',
				name:'serviceName',
				value:''
			},
			{
				xtype:'clearTextField',
				fieldLabel:'描述',
				name:'serviceConent',
				value:''
			},
			{
				xtype:'clearTextField',
				fieldLabel:'图片',
				name:'servicePhoto',
				value:''
			},
			{
				xtype:'clearTextField',
				fieldLabel:'价格',
				name:'servicePrice',
				value:''
			},
			{
				xtype:'numberfield',
				fieldLabel:'省id',
				name:'serviceProviceId',
				value:0
			},
			{
				xtype:'clearTextField',
				fieldLabel:'省名称',
				name:'serviceProviceName',
				value:''
			},
			{
				xtype:'numberfield',
				fieldLabel:'市id',
				name:'serviceCityId',
				value:0
			},
			{
				xtype:'clearTextField',
				fieldLabel:'市名称',
				name:'serviceCityName',
				value:''
			},
			{
				xtype:'clearTextField',
				fieldLabel:'服务方式',
				name:'serviceType',
				value:''
			},
			{
				xtype:'clearTextField',
				fieldLabel:'是否…方式',
				name:'isMobile',
				value:''
			},
			{
				xtype:'clearTextField',
				fieldLabel:'是否谈价',
				name:'isPrice',
				value:''
			},
			{
				xtype:'clearTextField',
				fieldLabel:'发布人id',
				name:'publisherId',
				value:''
			},
			{
				xtype:'clearTextField',
				fieldLabel:'发布人姓名',
				name:'publisherName',
				value:''
			},
			{
				xtype:'clearTextField',
				fieldLabel:'发布…方式',
				name:'publisherMobile',
				value:''
			},
			{
				xtype:'datefield',
				fieldLabel:'发布时间',
				name:'publishDate',
				value:new Date(),
				format:'Y-m-d'
			},
			{
				xtype:'clearTextField',
				fieldLabel:'发布经度',
				name:'lng',
				value:''
			},
			{
				xtype:'clearTextField',
				fieldLabel:'发布纬度',
				name:'lat',
				value:''
			},
			{
				xtype:'numberfield',
				fieldLabel:'有效时间',
				name:'validityPeriod',
				value:0
			},
			{
				xtype:'clearTextField',
				fieldLabel:'上架状态',
				name:'shelfStatus',
				value:''
			},
			{
				xtype:'clearTextField',
				fieldLabel:'备注',
				name:'remark',
				value:''
			}
		]
	},
	search:[
		{
			xtype:'clearTextField',
			fieldLabel:'',
			name:'serviceId',
			value:''
		},
		{
			xtype:'clearTextField',
			fieldLabel:'类别id',
			name:'%serviceCategoryId%',
			value:''
		},
		{
			xtype:'clearTextField',
			fieldLabel:'类别名称',
			name:'%serviceCategoryName%',
			value:''
		},
		{
			xtype:'clearTextField',
			fieldLabel:'名称',
			name:'%serviceName%',
			value:''
		},
		{
			xtype:'clearTextField',
			fieldLabel:'描述',
			name:'%serviceConent%',
			value:''
		},
		{
			xtype:'clearTextField',
			fieldLabel:'图片',
			name:'servicePhoto',
			value:''
		},
		{
			xtype:'clearTextField',
			fieldLabel:'价格',
			name:'%servicePrice%',
			value:''
		},
		{
			xtype:'numberfield',
			fieldLabel:'省id',
			name:'serviceProviceId',
			value:0
		},
		{
			xtype:'clearTextField',
			fieldLabel:'省名称',
			name:'%serviceProviceName%',
			value:''
		},
		{
			xtype:'numberfield',
			fieldLabel:'市id',
			name:'serviceCityId',
			value:0
		},
		{
			xtype:'clearTextField',
			fieldLabel:'市名称',
			name:'%serviceCityName%',
			value:''
		},
		{
			xtype:'clearTextField',
			fieldLabel:'服务方式',
			name:'%serviceType%',
			value:''
		},
		{
			xtype:'clearTextField',
			fieldLabel:'是否…方式',
			name:'%isMobile%',
			value:''
		},
		{
			xtype:'clearTextField',
			fieldLabel:'是否谈价',
			name:'%isPrice%',
			value:''
		},
		{
			xtype:'clearTextField',
			fieldLabel:'发布人id',
			name:'%publisherId%',
			value:''
		},
		{
			xtype:'clearTextField',
			fieldLabel:'发布人姓名',
			name:'%publisherName%',
			value:''
		},
		{
			xtype:'clearTextField',
			fieldLabel:'发布…方式',
			name:'%publisherMobile%',
			value:''
		},
		{
			xtype:'datefield',
			fieldLabel:'发布时间',
			name:'publishDate',
			value:'2016-07-25 01:35:51',format:'Y-m-d'
		},
		{
			xtype:'clearTextField',
			fieldLabel:'发布经度',
			name:'lng',
			value:''
		},
		{
			xtype:'clearTextField',
			fieldLabel:'发布纬度',
			name:'lat',
			value:''
		},
		{
			xtype:'numberfield',
			fieldLabel:'有效时间',
			name:'validityPeriod',
			value:0
		},
		{
			xtype:'clearTextField',
			fieldLabel:'上架状态',
			name:'%shelfStatus%',
			value:''
		},
		{
			xtype:'clearTextField',
			fieldLabel:'备注',
			name:'%remark%',
			value:''
		}
	],
	store:{
		fields:['serviceId','serviceCategoryId','serviceCategoryName','serviceName','serviceConent','servicePhoto','servicePrice','serviceProviceId','serviceProviceName','serviceCityId','serviceCityName','serviceType','isMobile','isPrice','publisherId','publisherName','publisherMobile','publishDate','lng','lat','validityPeriod','shelfStatus','remark'],
		sqlKey:'serviceInfo.selectList',
		type:'DB'
	},
	grid:[
		{ text: 'id',  dataIndex: 'serviceId' ,flex:1,hidden:true},
		{ text: '类别id',  dataIndex: 'serviceCategoryId' ,flex:1},
		{ text: '类别名称',  dataIndex: 'serviceCategoryName' ,flex:1},
		{ text: '名称',  dataIndex: 'serviceName' ,flex:1},
		{ text: '描述',  dataIndex: 'serviceConent' ,flex:1},
		{ text: '图片',  dataIndex: 'servicePhoto' ,flex:1},
		{ text: '价格',  dataIndex: 'servicePrice' ,flex:1},
		{ text: '省id',  dataIndex: 'serviceProviceId' ,flex:1},
		{ text: '省名称',  dataIndex: 'serviceProviceName' ,flex:1},
		{ text: '市id',  dataIndex: 'serviceCityId' ,flex:1},
		{ text: '市名称',  dataIndex: 'serviceCityName' ,flex:1},
		{ text: '服务方式',  dataIndex: 'serviceType' ,flex:1},
		{ text: '是否开启展示联系方式',  dataIndex: 'isMobile' ,flex:1},
		{ text: '是否谈价',  dataIndex: 'isPrice' ,flex:1},
		{ text: '发布人id',  dataIndex: 'publisherId' ,flex:1},
		{ text: '发布人姓名',  dataIndex: 'publisherName' ,flex:1},
		{ text: '发布人联系方式',  dataIndex: 'publisherMobile' ,flex:1},
		{ text: '发布时间',  dataIndex: 'publishDate' ,flex:1},
		{ text: '发布经度',  dataIndex: 'lng' ,flex:1},
		{ text: '发布纬度',  dataIndex: 'lat' ,flex:1},
		{ text: '有效时间',  dataIndex: 'validityPeriod' ,flex:1},
		{ text: '上架状态',  dataIndex: 'shelfStatus' ,flex:1},
		{ text: '备注',  dataIndex: 'remark' ,flex:1}
	]
}